//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webapi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class counter
    {
        public string type { get; set; }
        public string fun { get; set; }
        public int id { get; set; }
        public Nullable<int> value { get; set; }
    }
}
